builds:
  - name: ecflow-hpc
    type: hpc
    enabled: true
    config:
      platform: gnu-14.2.0
      install_type: module

      dependencies: |
        ecmwf/ecbuild@develop

      parallel: 64
      self_test: false

      stages:
        - name: python312
          modules:
            - boost/1.87.0
            - ninja
            - python3/3.12.9-01
            - qt/6.6.1
            - cmake/new
          cmake_options: >-
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DENABLE_ALL_TESTS=OFF
            -DBoost_ROOT=/usr/local/apps/boost/1.87.0/GNU/14.2
            -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.87.0/GNU/14.2/include
            -DBoost_PYTHON312_LIBRARY_RELEASE=/usr/local/apps/boost/1.87.0/GNU/14.2/lib/libboost_python312.so
            -DPython3_ROOT_DIR=/usr/local/apps/python3/3.12.9-01
            -DPython3_EXECUTABLE=/usr/local/apps/python3/3.12.9-01/bin/python3
            -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.12.9-01/include/python3.12
            -DPython3_LIBRARIES=/usr/local/apps/python3/3.12.9-01/lib64/libpython3.12.so
            -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.12.9-01/lib64


        - name: python311
          modules:
            - boost/1.84.0
            - ninja
            - python3/3.11.8-01
            - qt/5.12.0
            - cmake/new
          cmake_options: >-
            -DBoost_ROOT=/usr/local/apps/boost/1.84.0/GNU/8.5
            -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.84.0/GNU/8.5/include
            -DBoost_PYTHON311_LIBRARY_RELEASE=/usr/local/apps/boost/1.84.0/GNU/8.5/lib/libboost_python311.so
            -DPython3_ROOT_DIR=/usr/local/apps/python3/3.11.8-01
            -DPython3_EXECUTABLE=/usr/local/apps/python3/3.11.8-01/bin/python3
            -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.11.8-01/include/python3.11
            -DPython3_LIBRARIES=/usr/local/apps/python3/3.11.8-01/lib64/libpython3.11.so
            -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.11.8-01/lib64
          build_command: cd libs/pyext && make -j64
          install_command: |
            chmod u+w $INSTALL_PREFIX/lib
            cd libs/pyext && make install

        - name: python310
          modules:
            - boost/1.81.0
            - ninja
            - python3/3.10.10-01
            - qt/6.2.0
            - cmake/new
          cmake_options: >-
            -DBoost_ROOT=/usr/local/apps/boost/1.81.0/GNU/12.2
            -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.81.0/GNU/12.2/include
            -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.81.0/GNU/12.2/lib/libboost_python310.so
            -DPython3_ROOT_DIR=/usr/local/apps/python3/3.10.10-01
            -DPython3_EXECUTABLE=/usr/local/apps/python3/3.10.10-01/bin/python3
            -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.10.10-01/include/python3.10
            -DPython3_LIBRARIES=/usr/local/apps/python3/3.10.10-01/lib64/libpython3.10.so
            -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.10.10-01/lib64
          build_command: cd libs/pyext && make -j64
          install_command: |
            chmod u+w $INSTALL_PREFIX/lib
            cd libs/pyext && make install

      finalize:
        lock_permissions: true

release:
  enabled: false