cmake_options: >-
  -DBOOST_ROOT=${BOOST_ROOT_DIR}
  -DBOOST_INCLUDEDIR=${BOOST_INCLUDE_DIR}
  -DBOOST_LIBRARYDIR=${BOOST_LIB_DIR}
  -DBoost_DEBUG=ON 
  -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR}
  -DENABLE_STATIC_BOOST_LIBS=OFF
  -DINSTALL_PYTHON3_DIR=lib/python3/dist-packages
  -DENABLE_ALL_TESTS=ON
  -DENABLE_SSL=ON
  -DENABLE_SERVER=ON
  -DENABLE_UI=OFF
  -DCPACK_PACKAGE_NAME=ecflow
ctest_options: -L nightly -E s_test|s_zombies
dependencies: |
  ecmwf/ecbuild
dependency_branch: develop
parallelism_factor: 8
