build:
  modules:
    - boost
    - ninja
    - python3
    - qt
    - cmake/new
  dependencies:
    - ecmwf/ecbuild@develop
  parallel: 64
  cmake_options:
    - -DENABLE_ALL_TESTS=ON
  ctest_options:
    - -L nightly

gnu-14.2.0:
  build:
    modules:
      - boost/1.87.0
      - ninja
      - python3/3.12.9-01
      - qt/6.6.1
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
        -DBoost_ROOT=/usr/local/apps/boost/1.87.0/GNU/14.2
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.87.0/GNU/14.2/include
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.87.0/GNU/14.2/lib/libboost_python312.so
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.12.9-01
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.12.9-01/bin/python3
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.12.9-01/include/python3.12
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.12.9-01/lib64/libpython3.12.so
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.12.9-01/lib64
    ctest_options:
      - -L nightly

gnu-12.2.0:
  build:
    modules:
      - boost/1.81.0
      - ninja
      - python3/3.10.10-01
      - qt/6.2.0
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON 
        -DBoost_ROOT=/usr/local/apps/boost/1.81.0/GNU/12.2 
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.81.0/GNU/12.2/include 
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.81.0/GNU/12.2/lib/libboost_python310.so 
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.10.10-01 
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.10.10-01/bin/python3 
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.10.10-01/include/python3.10 
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.10.10-01/lib64/libpython3.10.so 
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.10.10-01/lib64
    ctest_options:
      - -L nightly

gnu-8.5.0:
  build:
    modules:
      - boost/1.84.0
      - ninja
      - python3/3.11.8-01
      - qt/5.12.0
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
    ctest_options:
      - -L nightly

intel-2025.0.1:
  build:
    modules:
      - boost/1.87.0
      - ninja
      - python3/3.12.9-01
      - qt/6.6.1
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
        -DCMAKE_CXX_COMPILER=icpx
        -DBoost_ROOT=/usr/local/apps/boost/1.87.0/INTEL/2025.0
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.87.0/INTEL/2025.0/include
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.87.0/INTEL/2025.0/lib/libboost_python312.so
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.12.9-01
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.12.9-01/bin/python3
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.12.9-01/include/python3.12
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.12.9-01/lib64/libpython3.12.so
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.12.9-01/lib64
    ctest_options:
      - -L nightly

intel-2021.4.0:
  build:
    modules:
      - boost/1.81.0
      - ninja
      - python3/3.10.10-01
      - qt/6.2.0
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
        -DCMAKE_CXX_COMPILER=icpx
        -DBoost_ROOT=/usr/local/apps/boost/1.81.0/INTEL/2021.4
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.81.0/INTEL/2021.4/include
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.81.0/INTEL/2021.4/lib/libboost_python310.so
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.10.10-01
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.10.10-01/bin/python3
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.10.10-01/include/python3.10
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.10.10-01/lib64/libpython3.10.so
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.10.10-01/lib64
    ctest_options:
      - -L nightly -E py3_

nvidia-24.11:
  build:
    modules:
      - boost/1.87.0
      - ninja
      - python3/3.12.9-01
      - qt/6.6.1
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
        -DBoost_ROOT=/usr/local/apps/boost/1.87.0/NVIDIA/24.11
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.87.0/NVIDIA/24.11/include
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.87.0/NVIDIA/24.11/lib/libboost_python312.so
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.12.9-01
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.12.9-01/bin/python3
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.12.9-01/include/python3.12
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.12.9-01/lib64/libpython3.12.so
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.12.9-01/lib64
    ctest_options: 
      - -L nightly 

nvidia-22.11:
  build:
    modules:
      - boost/1.81.0
      - ninja
      - python3/3.10.10-01
      - qt/5.12.0
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
        -DBoost_ROOT=/usr/local/apps/boost/1.81.0/NVIDIA/22.11
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.81.0/NVIDIA/22.11/include
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.81.0/NVIDIA/22.11/lib/libboost_python310.so
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.10.10-01
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.10.10-01/bin/python3
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.10.10-01/include/python3.10
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.10.10-01/lib64/libpython3.10.so
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.10.10-01/lib64
    ctest_options: 
      # disable all tests
      - --version

aocc-4.0.0:
  build:
    modules:
      - boost/1.81.0
      - ninja
      - python3/3.10.10-01
      - qt/6.2.0
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DENABLE_ALL_TESTS=ON
        -DBoost_ROOT=/usr/local/apps/boost/1.81.0/AMD/4.0
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.81.0/AMD/4.0/include
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.81.0/AMD/4.0/lib/libboost_python310.so
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.10.10-01
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.10.10-01/bin/python3
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.10.10-01/include/python3.10
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.10.10-01/lib64/libpython3.10.so
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.10.10-01/lib64
    ctest_options: 
      - -L nightly
