build:
  modules:
    - boost
    - ninja
    - python3
    - qt
    - cmake/new
  dependencies:
    - ecmwf/ecbuild@develop
  parallel: 64
  cmake_options:
    - -DENABLE_ALL_TESTS=ON
  ctest_options:
    - -L nightly

gnu-12.2.0:
  build:
    modules:
      - boost/1.81.0
      - ninja
      - python3/3.10.10-01
      - qt
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - >-
        -DENABLE_ALL_TESTS=ON 
        -DBoost_ROOT=/usr/local/apps/boost/1.81.0/GNU/12.2 
        -DBoost_INCLUDE_DIR=/usr/local/apps/boost/1.81.0/GNU/12.2/include 
        -DBoost_PYTHON310_LIBRARY_RELEASE=/usr/local/apps/boost/1.81.0/GNU/12.2/lib/libboost_python310.so 
        -DPython3_ROOT_DIR=/usr/local/apps/python3/3.10.10-01 
        -DPython3_EXECUTABLE=/usr/local/apps/python3/3.10.10-01/bin/python3 
        -DPython3_INCLUDE_DIRS=/usr/local/apps/python3/3.10.10-01/include/python3.10 
        -DPython3_LIBRARIES=/usr/local/apps/python3/3.10.10-01/lib64/libpython3.10.so 
        -DPython3_LIBRARY_DIRS=/usr/local/apps/python3/3.10.10-01/lib64
    ctest_options:
      - -L nightly

gnu-8.5.0:
  build:
    modules:
      - boost/1.84.0
      - ninja
      - python3/3.11.8-01
      - qt
      - cmake/new
    dependencies:
      - ecmwf/ecbuild@develop
    parallel: 64
    cmake_options:
      - -DENABLE_ALL_TESTS=ON
    ctest_options:
      - -L nightly
