# SPDX-FileCopyrightText: 2009- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

# To validate this file:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Ignored Paths
# -------------
ignore:
  - "3rdparty/cereal"
  - "3rdparty/cpp-httplib"
  - "3rdparty/json"
