message( STATUS "------------------------------------------------------" )

if(Boost_FOUND)
    message( STATUS " Boost_INCLUDE_DIRS                : [${Boost_INCLUDE_DIRS}]" )
    message( STATUS " Boost_LIBRARY_DIR_RELEASE         : [${Boost_LIBRARY_DIR_RELEASE}]" )
    message( STATUS " Boost_SYSTEM_LIBRARY              : [${Boost_SYSTEM_LIBRARY}]" )
    message( STATUS " Boost_THREAD_LIBRARY              : [${Boost_THREAD_LIBRARY}]" )
    message( STATUS " Boost_FILESYSTEM_LIBRARY          : [${Boost_FILESYSTEM_LIBRARY}]" )
    message( STATUS " Boost_PROGRAM_OPTIONS_LIBRARY     : [${Boost_PROGRAM_OPTIONS_LIBRARY}]" )
    message( STATUS " Boost_DATE_TIME_LIBRARY           : [${Boost_DATE_TIME_LIBRARY}]" )
    message( STATUS " Boost_UNIT_TEST_FRAMEWORK_LIBRARY : [${Boost_UNIT_TEST_FRAMEWORK_LIBRARY}]" )
    message( STATUS " Boost_TEST_EXEC_MONITOR_LIBRARY   : [${Boost_TEST_EXEC_MONITOR_LIBRARY}]" )
    message( STATUS " Boost_REGEX_LIBRARY               : [${Boost_REGEX_LIBRARY}]" )
    message( STATUS " Boost_PYTHON_LIBRARY              : [${Boost_PYTHON_LIBRARY}]" )
    message( STATUS " Boost_PYTHON27_LIBRARY            : [${Boost_PYTHON27_LIBRARY}]" )
    message( STATUS " Boost_PYTHON_LIBRARY_RELEASE      : [${Boost_PYTHON_LIBRARY_RELEASE}]" )
endif()

if( PYTHONINTERP_FOUND )
	message( STATUS "Python exec     : ${PYTHON_EXECUTABLE}" )
	message( STATUS "       include  : ${PYTHON_INCLUDE_DIRS}" )
	message( STATUS "       libs     : ${PYTHON_LIBRARIES}" )
endif()

if (ENABLE_SSL)
    ecbuild_info("OpenSSL VERSION  ${OPENSSL_VERSION}")
    ecbuild_info("        LIBS     ${OPENSSL_LIBRARIES}")
    ecbuild_info("        INCLUDES ${OPENSSL_INCLUDE_DIR}")
endif()