/*
** Generated by X-Designer
*/
#ifndef _uifsb_h
#define _uifsb_h

#define XD_MOTIF

#include <xdclass.h>

class fsb_shell_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget fsb_shell;
	Widget form_;
	Widget label_;
public:
	static void helpCB( Widget, XtPointer, XtPointer );
	virtual void helpCB( Widget, XtPointer ) = 0;
	static void cancelCB( Widget, XtPointer, XtPointer );
	virtual void cancelCB( Widget, XtPointer ) = 0;
	static void okCB( Widget, XtPointer, XtPointer );
	virtual void okCB( Widget, XtPointer ) = 0;
};

typedef fsb_shell_c *fsb_shell_p;


extern fsb_shell_p fsb_shell;


#endif
