/*
** Generated by X-Designer
*/
#ifndef _uimessages_h
#define _uimessages_h

#define XD_MOTIF

#include <xdclass.h>

class messages_form_c: public xd_XmForm_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget messages_form;
	Widget text_;
	Widget tools_;
public:
	static void searchCB( Widget, XtPointer, XtPointer );
	virtual void searchCB( Widget, XtPointer ) = 0;
	static void externalCB( Widget, XtPointer, XtPointer );
	virtual void externalCB( Widget, XtPointer ) = 0;
};

typedef messages_form_c *messages_form_p;
class script;
typedef script *script_p;


extern script_p messages_form;


#endif
