/*
** Generated by X-Designer
*/
#ifndef _uipasswd_h
#define _uipasswd_h

#define XD_MOTIF

#include <xdclass.h>

class passwd_shell_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget passwd_shell;
	Widget form_;
	Widget password;
	Widget passwd_;
	Widget user_;
	Widget label_;
public:
	static void modifyCB( Widget, XtPointer, XtPointer );
	virtual void modifyCB( Widget, XtPointer ) = 0;
	static void helpCB( Widget, XtPointer, XtPointer );
	virtual void helpCB( Widget, XtPointer ) = 0;
	static void cancelCB( Widget, XtPointer, XtPointer );
	virtual void cancelCB( Widget, XtPointer ) = 0;
	static void okCB( Widget, XtPointer, XtPointer );
	virtual void okCB( Widget, XtPointer ) = 0;
};

typedef passwd_shell_c *passwd_shell_p;


extern passwd_shell_p passwd_shell;


#endif
