/*
** Generated by X-Designer
*/
#ifndef _uiwhy_h
#define _uiwhy_h

#define XD_MOTIF

#include <xdclass.h>

class why_form_c: public xd_XmForm_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget why_form;
	Widget text_;
public:
	static void hyperCB( Widget, XtPointer, XtPointer );
	virtual void hyperCB( Widget, XtPointer ) = 0;
};

typedef why_form_c *why_form_p;


extern why_form_p why_form;


#endif
