{% set name = "ecFlow" %}
{% set git_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0').lstrip('v') %}
{% set version = git_tag.replace('-', '') | lower %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - python
    - libboost-python-devel
    - qt-main
    - xorg-libxfixes  # [linux]
    - zlib  # [linux]
    - libxcrypt  # [linux]
  run:
    - python
    - qt-main
    - libboost-python-devel
    - zlib  # [linux]
    - libxcrypt  # [linux]

test:
  commands:
    - ecflow_client --help
    - ecflow_server --help
    - ecflow_standalone -v

about:
  home: https://ecflow.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecFlow

extra:
  recipe-maintainers:
    - marcosbento
    - iainrussell