/*
 * Copyright 2009- ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation
 * nor does it submit to any jurisdiction.
 */

#include "ecflow/core/PrintStyle.hpp"
#include "ecflow/node/Alias.hpp"
#include "ecflow/node/Task.hpp"
#include "ecflow/node/formatter/DefsWriter.hpp"
#include "ecflow/python/DefsDoc.hpp"
#include "ecflow/python/ExportCollections.hpp"
#include "ecflow/python/NodeUtil.hpp"
#include "ecflow/python/PythonBinding.hpp"
#include "ecflow/python/PythonUtil.hpp"

namespace {

// Task

std::shared_ptr<Task> Task_init(const std::string& name, const py::args& args, const py::kwargs& kwargs) {
    auto node = std::make_shared<Task>(name);
    NodeUtil::add(*node, args);
    NodeUtil::add(*node, kwargs);
    return node;
}

task_ptr Task_enter(task_ptr self) {
    return self;
}

bool Task_exit(task_ptr self, const py::object& type, const py::object& value, const py::object& traceback) {
    return false;
}

std::string Task_str(task_ptr self) {
    return ecf::as_string(*self, PrintStyleHolder::getStyle());
}

auto Task_len(task_ptr self) {
    return self->aliases().size();
}

// Alias

std::string Alias_str(alias_ptr self) {
    return ecf::as_string(*self, PrintStyleHolder::getStyle());
}

} // namespace

void export_Task(py::module& m) {

    py::class_<Submittable, Node, std::shared_ptr<Submittable>>(m, "Submittable", DefsDoc::submittable_doc())

        .def("get_jobs_password",
             &Submittable::jobsPassword,
             py::return_value_policy::reference,
             "The password. This generated by server")
        .def("get_process_or_remote_id",
             &Submittable::process_or_remote_id,
             py::return_value_policy::reference,
             "The process or remote id of the running job")
        .def("get_try_no", &Submittable::tryNo, "The current try number as a string.")
        .def("get_int_try_no", &Submittable::try_no, "The current try number as integer.")
        .def("get_aborted_reason",
             &Submittable::abortedReason,
             py::return_value_policy::reference,
             "If node was aborted and a reason was provided, return the string");

    py::class_<Task, Submittable, std::shared_ptr<Task>>(m, "Task", DefsDoc::task_doc())

        .def(py::init(&Task_init), DefsDoc::task_doc())
        .def(py::init<const std::string&>(), py::arg("name"))
        .def(py::self == py::self)
        .def("__enter__", &Task_enter)
        .def("__exit__", &Task_exit)
        .def("__str__", &Task_str)
        .def("__copy__", pyutil_copy_object<Task>)
        .def("__len__", &Task_len)
        .def("__iter__", &Task::aliases)
        .def_property_readonly("aliases", &Task::aliases, "Returns a list of aliases")
        .def_property_readonly("nodes", &Task::aliases, "Returns a list of aliases");

    py::class_<Alias, Submittable, std::shared_ptr<Alias>>(m, "Alias", DefsDoc::alias_doc())

        .def(py::self == py::self)
        .def("__str__", &Alias_str)
        .def("__copy__", pyutil_copy_object<Alias>);
}
