services:

  revproxy:
    build: ./revproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./revproxy/server:/usr/share/nginx/html/server
      - ./revproxy/cfgs/nginx/default.conf:/etc/nginx/conf.d/default.conf

  authotron:
    image: eccr.ecmwf.int/auth-o-tron/auth-o-tron:0.2.8
    ports:
      - "8080:8080"
    volumes:
      - ./authotron/config.yaml:/app/config.yaml

  ecflow-deploy:
    build: 
      context: ./ecflow
      target: deploy
    ports:
      - "8888:8888"
    volumes:
      - ./ecflow/deploy/workspace:/workspace

  ecflow-builder:
    build: 
      context: ./ecflow
      target: builder
    profiles:
      - development
