/*
** Generated by X-Designer
*/
#ifndef _uicolors_h
#define _uicolors_h

#define XD_MOTIF

#include <xdclass.h>

class colors_form_c: public xd_XmForm_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget colors_form;
	Widget form_;
public:
	static void useCB( Widget, XtPointer, XtPointer );
	virtual void useCB( Widget, XtPointer ) = 0;
	static void changedCB( Widget, XtPointer, XtPointer );
	virtual void changedCB( Widget, XtPointer ) = 0;
};

typedef colors_form_c *colors_form_p;


extern colors_form_p colors_form;


#endif
