/*
** Generated by X-Designer
*/
#ifndef _uierror_h
#define _uierror_h

#define XD_MOTIF

#include <xdclass.h>

class error_shell_c: public xd_XmDialog_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget error_shell;
	Widget form_;
	Widget label_;
public:
	static void helpCB( Widget, XtPointer, XtPointer );
	virtual void helpCB( Widget, XtPointer ) = 0;
	static void cancelCB( Widget, XtPointer, XtPointer );
	virtual void cancelCB( Widget, XtPointer ) = 0;
	static void okCB( Widget, XtPointer, XtPointer );
	virtual void okCB( Widget, XtPointer ) = 0;
};

typedef error_shell_c *error_shell_p;


extern error_shell_p error_shell;


#endif
