/*
** Generated by X-Designer
*/
#ifndef _uijob_h
#define _uijob_h

#define XD_MOTIF

#include <xdclass.h>

class job_form_c: public xd_XmForm_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget job_form;
	Widget text_;
	Widget name_;
	Widget tools_;
public:
	static void searchCB( Widget, XtPointer, XtPointer );
	virtual void searchCB( Widget, XtPointer ) = 0;
	static void externalCB( Widget, XtPointer, XtPointer );
	virtual void externalCB( Widget, XtPointer ) = 0;
};

typedef job_form_c *job_form_p;
class script;
typedef script *script_p;


extern script_p job_form;


#endif
