/*
** Generated by X-Designer
*/
#ifndef _uimanual_h
#define _uimanual_h

#define XD_MOTIF

#include <xdclass.h>

class manual_form_c: public xd_XmForm_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget manual_form;
	Widget text_;
	Widget tools_;
public:
	static void externalCB( Widget, XtPointer, XtPointer );
	virtual void externalCB( Widget, XtPointer ) = 0;
	static void searchCB( Widget, XtPointer, XtPointer );
	virtual void searchCB( Widget, XtPointer ) = 0;
};

typedef manual_form_c *manual_form_p;
class manual;
typedef manual *manual_p;


extern manual_p manual_form;


#endif
