/*
** Generated by X-Designer
*/
#ifndef _uiuser_h
#define _uiuser_h

#define XD_MOTIF

#include <xdclass.h>

class user_form_c: public xd_XmForm_c {
public:
	virtual void create (Widget parent, char *widget_name = NULL);
protected:
	Widget user_form;
	Widget form_;
public:
	static void useCB( Widget, XtPointer, XtPointer );
	virtual void useCB( Widget, XtPointer ) = 0;
	static void changedCB( Widget, XtPointer, XtPointer );
	virtual void changedCB( Widget, XtPointer ) = 0;
};

typedef user_form_c *user_form_p;


extern user_form_p user_form;


#endif
