# SPDX-FileCopyrightText: 2009- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME "ecflow")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}_${CMAKE_SYSTEM_PROCESSOR}")

if (CUSTOM_DEBIAN_PACKAGE_VERSION)
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CUSTOM_DEBIAN_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")
  ecbuild_info("Custom Debian package version: ${CPACK_PACKAGE_FILE_NAME}")
else()
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")
  ecbuild_info("Default Debian package version: ${CPACK_PACKAGE_FILE_NAME}")
endif()

set(DEPENDS "libboost-all-dev")
if(ENABLE_SSL)
  set(DEPENDS "${DEPENDS}, libssl-dev")
endif()
if(ENABLE_UI)
  if(Qt5_FOUND)
    set(DEPENDS "${DEPENDS}, libqt5widgets5, libqt5network5, libqt5gui5, libqt5core5a")
  elseif(Qt6_FOUND)
    set(DEPENDS "${DEPENDS}, libqt6widgets6, libqt6network6, libqt6gui6, libqt6core6")
  else()
    ecbuild_critical("ENABLE_UI is set but neither Qt5 nor Qt6 was found - cannot determine the Debian package's Qt dependencies")
  endif()
endif()
set(CPACK_DEBIAN_PACKAGE_DEPENDS "${DEPENDS}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "software@ecmwf.int")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")

include(CPack)
