name: cd

on:
  push: ~
  #push:
  #  tags:
  #    - '[0-9]+.[0-9]+.[0-9]+'
  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  deploy:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/create-package.yml@add-skip_matrix_jobs-to-create-package
    with:
      skip_checks: true
    secrets: inherit
