name: cd

on:
  push
  #push:
  #  tags:
  #    - '[0-9]+.[0-9]+.[0-9]+'

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  deploy:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/create-package.yml@v2
    with:
      skip_checks: true
    secrets: inherit
