name: extra

on:
  # Trigger the workflow on every push
  push:
    branches:
      - '**'
    tags:
      - '**'

  # Trigger the workflow manually
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]

jobs:

  # Run 'extra' build
  build-gcc:
    name: build
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}

    strategy:
      max-parallel: 4
      matrix:
        os:
          - alpine-3.23
          - arch-20251019
          - debian-11.11
          - debian-12.12
          - debian-13.2
          - fedora-37
          - fedora-42
          - ubuntu-22.04
          - ubuntu-24.04
          - almalinux-9.6
          - almalinux-10.1
        preset:
          - linux.gcc.all.relwithdebinfo
          - linux.clang.all.relwithdebinfo
        jobs: [ 4 ]

    runs-on: [self-hosted, Linux, platform-builder-docker-xl]

    container:
      image: marcosbento/lumen:${{ matrix.os }}
      options: --user root

    steps:

      - name: Display build context
        run: |
          echo "Working directory: ${{ github.workspace }}"
          echo "Environment:"
          echo "$(env)"

      - name: Checkout 'ecbuild'
        uses: actions/checkout@v4
        with:
          repository: ecmwf/ecbuild
          path: ecbuild

      - name: Checkout 'ecflow'
        uses: actions/checkout@v4
        with:
          path: ecflow

      - name: Configure ecflow
        run: |
          cd ${RUNNER_WORKSPACE}/ecflow/ecflow
          cmake --preset ${{ matrix.preset }}

      - name: Build ecflow
        run: |
          cd ${RUNNER_WORKSPACE}/ecflow/ecflow
          cmake --build --preset ${{ matrix.preset }} --jobs ${{ matrix.jobs }}

      - name: Test ecflow
        run: |
          cd ${RUNNER_WORKSPACE}/ecflow/ecflow
          ctest --preset  ${{ matrix.preset }} --output-on-failure -L nightly -j ${{ matrix.jobs }}

      - name: Lint ecflow
        if: ${{ matrix.preset == 'linux.clang.all.relwithdebinfo' && matrix.os == 'ubuntu-24.04' }}
        run: |
          cd ${RUNNER_WORKSPACE}/ecflow/ecflow
          run-clang-tidy -j ${{ matrix.jobs }} -p ${RUNNER_WORKSPACE}/ecflow/ecflow/.deploy/build/${{ matrix.preset }} | tee clang-tidy-report.txt

      - name: Archive lint report 
        if: ${{ matrix.preset == 'linux.clang.all.relwithdebinfo' && matrix.os == 'ubuntu-24.04' }}
        uses: actions/upload-artifact@v4
        with:
          name: cling-tidy-report
          path: ${RUNNER_WORKSPACE}/ecflow/ecflow/clang-tidy-report.txt
