# Manage labels of pull requests that originate from forks
name: label-public-pr
 
on:
  pull_request_target:
    types: [opened, synchronize]
 
jobs:
  label-dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  label:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/label-pr.yml@v2
