# SPDX-FileCopyrightText: 2009- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

# Manage labels of pull requests that originate from forks
name: label-public-pr
 
on:
  pull_request_target:
    types: [opened, synchronize]
 
jobs:
  label:
    uses: ecmwf/reusable-workflows/.github/workflows/label-pr.yml@v2
